const BASE = process.env.PUBLIC_URL;

export const worksData = [
  {
    id: 1,
    title: 'DreamMayday',
    category: 'Communication',
    duration: '3 months',
    technology: ['Unity', 'C#'],
    description: 'BitSummit Gamejam 2025にて総合グランプリ（最優秀賞）を受賞した協力コミュニケーションゲーム',
    detailedDescription: {
      overview: 'BitSummit Gamejam 2025にて初対面の10人で制作し、展示したプロジェクト',
      content: '通常のモニターと球状のモニター（8枚目）を用いた2画面マルチプレイの協力コミュニケーションゲーム。\n2人のプレイヤーは「ドリームサポーター」として、夢と現実それぞれの立場から住人（NPC）の睡眠を守ります。夢側のプレイヤーは眠る住人の夢を観察し、異変を検知してもう片方のプレイヤーに共有します。現実側のプレイヤーはその情報をもとに原因を特定し、適切に対処します。2人の連携によって、朝まで快適な眠りを維持することを目指すゲームです。',
      role: '企画立案 \n仕様書作成 \nマネジメント（タスク割り当てやスケジュール調整） \nマルチディスプレイ制御プログラムの実装\n 複数シーンのAdditive読み込みの実装 \nソース管理',
    },
    features: ['総合グランプリ受賞', 'チーム開発', 'BSGM2025', '球状モニター', '2画面', 'マルチプレイ', '多数回展示'],
    image: `${BASE}/Image/works/DreamMayday/DreamMayday.png`,
    links: {
      itch: 'https://bitsummit-gamejam.itch.io/dreammayday',
      github: 'https://github.com/BSGJ2025-w-12/DreamMayday_Scripts',
      Youtube: 'https://youtu.be/t4DQaSw2VJk?si=8auwvXWbhMSgRNEL',
      note: 'https://note.com/taka10822/n/nd1916fb6d500',
      website: 'https://gameparade.creators-guild.com/works/3186',
    },
  },
  {
    id: 2,
    title: 'CRASH REPORT',
    category: '3D Action',
    duration: '3 months',
    technology: ['Unity', 'C#', 'Blender'],
    description: '自身で設立した学生ゲーム制作団体「TOMSN」で制作した第1弾のゲーム',
    detailedDescription: {
      overview: 'アルバイト先のメンバーを誘い、初めて共同でゲーム開発した3Dアクションゲーム',
      content: '学生5人のチーム「TOMSN」（現在は8人）を設立し、第1弾として制作した3Dアクションゲーム。\nユニークな敵が多数出現するステージ内にレーザーを駆使して突き進み、すべての敵を撃破することでクリアとなる、爽快感のあるゲームです。',
      role: '企画立案 \n仕様書作成 \nマネジメント（タスク割り当てやスケジュール調整） \n敵の実装（ラビット、ラムダオクトパス） \nステージ制作 \n一部敵の攻撃で使用する3Dモデルの作成',
    },
    features: ['初の共同ゲーム開発', 'アジャイル開発', 'チーム設立', '第1弾'],
    image: `${BASE}/Image/works/CrashReport/CRASH REPORT.png`,
    links: {
      unityroom: 'https://unityroom.com/games/crash_report',
      github: 'https://github.com/TOMSNtomsn/CRASH-REPORT',
      Youtube: 'https://youtu.be/TGv2T4rzuc0?si=Gj0YHfU6Lz7dcp_I',
      note: 'https://note.com/taka10822/n/n9265ce5cd160',
      website: 'https://gameparade.creators-guild.com/works/3163',
    },
  },
  {
    id: 3,
    title: '研究室からの脱出',
    category: 'Escape',
    duration: '2 months',
    technology: ['Unity', 'C#', '3D Scan', 'Photon PUN2', 'Blender', 'Mixamo'],
    description: '研究室のメンバーで制作した現実空間をゲーム舞台に落とし込んだマルチプレイ脱出ゲーム',
    detailedDescription: {
      overview: '研究室のメンバーで制作した研究室や教授、私が登場するマルチプレイ脱出ゲーム',
      content: '教授の定年により研究室が数年後に閉鎖されることを受け、研究室空間をデジタル上に残すことを目的に、5人で制作したマルチプレイ脱出ゲーム。\n私のバイクの車種やメンバーの執筆論文の参考文献数など、内輪ネタを活かしたギミックを多数実装しています。さらに、天気APIを用いた仕掛けやマルチプレイならではの協力要素も取り入れています。なお、個人情報保護の観点から本作品は非公開としています。',
      role: '企画立案 \n仕様書作成 \nマネジメント（タスク割り当てやスケジュール調整） \n人物のスキャンとモデリング \nマルチプレイ実装（サーバー接続や同期処理） \nソース管理 ',
    },
    features: ['チーム開発', 'マルチプレイ', '3Dスキャン', '空間保存'],
    image: `${BASE}/Image/works/MultiEscape/MultiEscape.png`,
    links: {
      github: 'https://github.com/Taka100822/LabEscapeGame',
      note: 'https://note.com/taka10822/n/n9031b5fbc073?sub_rt=share_pw',
    },
  },
  {
    id: 4,
    title: 'POGO・Stadium',
    category: 'Action & Strategy',
    duration: '10 months',
    technology: ['Unity', 'C#', 'Tiled'],
    description: 'アルバイトとして参加した新感覚のホッピング陣取りバトルゲーム',
    detailedDescription: {
      overview: 'アルバイトでプランナー兼プログラマーとして開発に参加した戦略アクションゲーム',
      content: '未来都市の夜空に浮かぶバトルスタジアムを舞台とした、アクションと戦略性を組み合わせた陣取りゲーム。\nプレイヤーはフィールドを構成するブロックの形状を読み取りながらエリアを切り取り、自身の陣地を拡大していきます。獲得したエネルギーを活用することで攻撃が可能となり、移動ルートの確保や陣地管理といった判断が重要です。',
      role: '演出の仕様作成 \nローカライズデータ作成 \nステージ制作 \nブロック落下演出の実装 \n背景制作補助',
    },
    features: ['学生アルバイト', '収益化タイトル', '中規模チーム開発'],
    image: `${BASE}/Image/works/PogoStadium/PogoStadium.png`,
    links: {
      steam: 'https://store.steampowered.com/app/3672410/POGO_Stadium',
      nintendo: 'https://store-jp.nintendo.com/item/software/D70010000104217',
      website: 'https://pogostadium.com',
      Youtube: 'https://youtu.be/1p6bkLrbkSs?si=lP8HiRBbq7188G88',
    },
  },
  {
    id: 5,
    title: 'わけあい',
    category: '3D Pazzle',
    duration: '1 week',
    technology: ['Unity', 'C#'],
    description: 'Unity1WeekGamejamで制作したハートを分け合い、町を明るくする3Dゲーム',
    detailedDescription: {
      overview: 'Unity1WeekGameJamの「あい」というテーマで制作した作品',
      content: 'ハートを住民に分け与えることで、暗い町を明るくしていく3Dパズルゲーム。\nプレイヤーは自身のハートを愛が不足している住民に分け与えていきますが、与えすぎてハートがなくなるとゲームオーバーとなります。\nハートをくれる住民と必要としている住民を見極めながら、町全体に愛を広げていきます。',
      role: '個人制作のためすべて',
    },
    features: ['個人制作', 'Unity Asset使用', 'Unity1WeekGameJam初参加作品'],
    image: `${BASE}/Image/works/Wakeai/Wakeai.png`,
    links: {
      unityroom: 'https://unityroom.com/games/wakeai',
      github: 'https://github.com/Taka100822/Unity1WeekGameJam_1st',
      note: 'https://note.com/taka10822/n/n25c7fc449fc2?sub_rt=share_pw',
    },
  },
  {
    id: 6,
    title: '研究用ゲーム',
    category: '2D Action',
    duration: '5 months',
    technology: ['Unity', 'C#', 'Python', 'R'],
    description: 'ゲームの視覚情報に関する研究のために作成した2Dアクションゲーム',
    detailedDescription: {
      overview: 'ゲームのテキストの提示数がゲーム体験に与える影響を調査するために制作したゲーム',
      content: '学部卒業研究「2Dアクションゲームのテキストによる視覚提示の多寡がプレイヤの主観とスコアに及ぼす影響」の実験用に制作したゲーム。\n実験参加者は3つのステージをそれぞれのテキスト表示数パターンでプレイし、各ステージ終了後にアンケートに回答しました。そこで得られた主観評価と、ゲームログから得られる客観的指標（リトライ回数やクリアタイム）をもとに、テキスト表示数がゲーム体験に与える影響を統計的に分析しました。\nこの研究は最終的に学会にて発表しました。',
      role: '個人制作のためすべて',
    },
    features: ['Unity初作品', '研究用途', 'データ収集機能', 'TileMap', 'ゲームログ分析'],
    image: `${BASE}/Image/works/ReserchGame/ReserchGame.png`,
    links: {
      github: 'https://github.com/Taka100822/Graduation-Study',
    },
  },
  {
    id: 7,
    title: 'Dear you, FROM FAN （ペラ1）',
    category: 'Proposal',
    duration: '1 week',
    technology: ['PowerPoint', 'Unity'],
    description: '株式会社バンダイナムコスタジオ様の主催の「ゲームアイディア創造コンテスト」にて入賞',
    detailedDescription: {
      overview: 'バンダイナムコスタジオ様のゲームアイディア創造コンテストにて入賞したペライチ',
      content: 'アイドルを支える裏方として、ファンレターやプレゼントを検閲し、安全とアイドルの精神を守るゲーム。\nプレイヤーは日々変化する検閲ルールをもとに、郵便物を制限時間内に正確に仕分けていきます。本作の特徴は、「規則を守る責任」と「ファンの想いを届けたい感情」の間で揺れ動く心理的な葛藤にあります。誤った判断はアイドルへの被害や信頼関係の損失につながるため、正確さと判断力が求められます。\n単なる作業ゲームではなく、裏方としてアイドルを支える責任とプレッシャーを体験できるアドベンチャーゲームです。',
      role: '個人制作のためすべて',
    },
    features: ['企画書', '入賞作品'],
    image: `${BASE}/Image/works/Dear/Dear.png`,
    links: {
      pdf: `${BASE}/PDF/Dear.pdf`,
    },
  },
  {
    id: 8,
    title: 'チャットアプリ',
    category: 'Web App',
    duration: '1 week',
    technology: ['HTML', 'JavaScript', 'Nuxt.js', 'Vuetify', 'Tailwind CSS', 'Firebase'],
    description: 'インターンシップで制作したチャットWebアプリケーション',
    detailedDescription: {
      overview: 'インターンでフロントエンド開発の技術習得を目的として制作したWebアプリ',
      content: 'Nuxt.jsを使用して制作したチャットアプリケーション。\nデータベース連携を行い、ログイン機能を実装し、リアルタイムでチャットすることができます。',
      role: '個人開発のためすべて',
    },
    features: ['リアルタイムチャット', 'ログイン機能', 'データベース'],
    image: `${BASE}/Image/works/chatApp/chatApp.png`,
    links: {
      github: 'https://github.com/Taka100822/chat-app',
    },
  },
  {
    id: 9,
    title: '冷蔵庫管理アプリ',
    category: 'Web App',
    duration: '3 months',
    technology: ['Vue.js', 'Nuxt.js'],
    description: '研究室の冷蔵庫内食品・飲料品管理のためのWebアプリ',
    detailedDescription: {
      overview: 'フロントエンドの一部分を担当した冷蔵庫内食品・飲料品管理Webアプリケーション',
      content: '初めてチーム開発で制作した冷蔵庫内の食品・飲料品管理Webアプリケーション。\n商品のバーコードをリーダーで読み込ませることで自動で登録が行われます。主な機能は登録、削除、更新およびリストの表示です。',
      role: '登録モーダルの設計と実装',
    },
    features: ['初チーム開発', 'フロントエンド担当', 'UI/UX設計'],
    image: `${BASE}/Image/works/fridge-manager/fridge-manager.png`,
    links: {
      github: 'https://github.com/KIT-HI-ProgrammingContestGroupC/fridge-manager',
    },
  },
];
