const BASE = process.env.PUBLIC_URL;

export const worksData = [
  {
    id: 1,
    title: 'DreamMayday',
    category: '2D & HD-2D Action',
    duration: '3ヶ月',
    technology: ['Unity', 'C#'],
    description: 'BitSummit Gamejam 2025にてゲームジャム総合グランプリを受賞した協力コミュニケーションゲーム',
    detailedDescription: {
      overview: 'BitSummit Gamejam 2025に向けてチームで制作したプロジェクト。',
      gameContent: '球状モニターを使った2画面マルチプレイの協力コミュニケーションゲーム。BitSummit Gamejam 2025にてゲームジャム総合グランプリを受賞。',
      role: 'プランナーとして進行管理や仕様書作成を担当しつつ、プログラマーとしてシステムの制御・マルチディスプレイ対応・複数シーンのAdditive読み込みの実装とソース管理を担当。',
    },
    features: ['チーム開発', 'BSGM2025', '球状モニター', '2画面', 'マルチプレイ'],
    image: `${BASE}/Image/works/DreamMayday/DreamMayday.png`,
    links: {
      itch: 'https://bitsummit-gamejam.itch.io/dreammayday',
      github: 'https://github.com/BSGJ2025-w-12/DreamMayday_Scripts',
      Youtube: 'https://youtu.be/t4DQaSw2VJk?si=8auwvXWbhMSgRNEL',
      note: 'https://note.com/taka10822/n/nd1916fb6d500',
      website: 'https://gameparade.creators-guild.com/works/3186',
    },
  },
  {
    id: 2,
    title: 'CRASH REPORT',
    category: '3D Action',
    duration: '3ヶ月',
    technology: ['Unity', 'C#', 'Blender'],
    description: '自身で立ち上げた学生チーム「TOMSN」で制作した3Dアクションゲーム',
    detailedDescription: {
      overview: '自身でチームを立ち上げ、初めてのチーム開発プロジェクトとして制作。アジャイル開発を取り入れながら進行した。',
      gameContent: '学生5人のチーム「TOMSN」で制作した3Dアクションゲーム。',
      role: 'プログラマーとプランナーの両方を担当し、ゲームシステムの設計から実装まで幅広く関わった。チーム開発でのコミュニケーションと進行管理も担当。',
    },
    features: ['チーム開発', 'アジャイル開発', 'Probuilder', '3DCG'],
    image: `${BASE}/Image/works/CrashReport/CRASH REPORT.png`,
    links: {
      unityroom: 'https://unityroom.com/games/crash_report',
      github: 'https://github.com/TOMSNtomsn/CRASH-REPORT',
      Youtube: 'https://youtu.be/TGv2T4rzuc0?si=Gj0YHfU6Lz7dcp_I',
      note: 'https://note.com/taka10822/n/n9265ce5cd160',
      website: 'https://gameparade.creators-guild.com/works/3163',
    },
  },
  {
    id: 3,
    title: '研究室からの脱出',
    category: 'Escape',
    duration: '2ヶ月',
    technology: ['Unity', 'C#', '3D Scan', 'Photon PUN2'],
    description: '研究室のチームで制作したマルチプレイ脱出ゲーム',
    detailedDescription: {
      overview: '研究室が数年以内に閉鎖されるため、3Dスキャナーで空間をデジタル保存し、そのデータをそのままゲームのステージとして使用した。',
      gameContent: '研究室のメンバーと制作した2人協力型マルチプレイ脱出ゲーム。個人情報保護の観点により非公開。',
      role: 'ネットワーク機能（Photon PUN2）の実装とゲームバランスの調整を担当。',
    },
    features: ['チーム開発', '協力型謎解き', 'マルチプレイ機能', '3Dスキャン'],
    image: `${BASE}/Image/works/MultiEscape/MultiEscape.png`,
    links: {
      github: 'https://github.com/Taka100822/LabEscapeGame',
      note: 'https://note.com/taka10822/n/n9031b5fbc073?sub_rt=share_pw',
    },
  },
  {
    id: 4,
    title: 'POGO・Stadium',
    category: 'Action & Strategy',
    duration: '10ヶ月',
    technology: ['Unity', 'C#'],
    description: '新感覚のホッピング陣取りバトルゲーム',
    detailedDescription: {
      overview: 'アルバイトとして参加した中規模チームでの開発プロジェクト。実際に収益が発生するタイトルの開発に携わることで、ゲーム制作のプロセスやマーケティングの重要性を実感した。',
      gameContent: 'ホッピングで陣地を奪い合う新感覚のバトルゲーム。Steam・Nintendo Switchにてリリース済みの収益化タイトル。',
      role: '企画面では演出の仕様作成・ローカライズデータ作成・ステージ制作を担当。実装面では自ら設計した演出の実装や背景制作を行った。',
    },
    features: ['学生アルバイト', '収益化タイトル', '中規模チーム開発'],
    image: `${BASE}/Image/works/PogoStadium/PogoStadium.png`,
    links: {
      steam: 'https://store.steampowered.com/app/3672410/POGO_Stadium',
      nintendo: 'https://store-jp.nintendo.com/item/software/D70010000104217',
      website: 'https://pogostadium.com',
      Youtube: 'https://youtu.be/1p6bkLrbkSs?si=lP8HiRBbq7188G88',
    },
  },
  {
    id: 5,
    title: 'わけあい',
    category: '3D Action',
    duration: '1週間',
    technology: ['Unity', 'C#'],
    description: 'ハートを分け合って町を明るくするゲーム',
    detailedDescription: {
      overview: 'Unity1WeekGameJamの「あい」というテーマで制作。1週間という制約の中で企画・実装・調整まで一人で完結させた。',
      gameContent: 'プレイヤーがハートを集めて町の人々に分け与えることで、暗い町を明るくしていく3Dアクションゲーム。',
      role: '個人開発のため企画・実装・デバッグ・調整すべてを一人で担当。',
    },
    features: ['個人開発', 'Asset使用', 'Unity1WeekGameJam参加作品'],
    image: `${BASE}/Image/works/Wakeai/Wakeai.png`,
    links: {
      unityroom: 'https://unityroom.com/games/wakeai',
      github: 'https://github.com/Taka100822/Unity1WeekGameJam_1st',
      note: 'https://note.com/taka10822/n/n25c7fc449fc2?sub_rt=share_pw',
    },
  },
  {
    id: 6,
    title: '研究用ゲーム',
    category: '2D Action',
    duration: '5ヶ月',
    technology: ['Unity', 'C#'],
    description: 'ゲームの視覚情報に関する研究のために作成した2Dアクションゲーム',
    detailedDescription: {
      overview: '卒業研究の一環として制作。プレイヤーの行動データを詳細に記録・分析できる仕組みを設計・実装した。',
      gameContent: '視覚情報の多寡がプレイヤー体験に与える影響を調査するための2Dアクションゲーム。遊ぶにはコントローラーが必要。',
      role: '個人開発のため企画・設計・実装・実験設計すべてを一人で担当。',
    },
    features: ['Unity初作品', '研究用途', 'データ収集機能', 'TileMap'],
    image: `${BASE}/Image/works/ReserchGame/ReserchGame.png`,
    links: {
      github: 'https://github.com/Taka100822/Graduation-Study',
    },
  },
  {
    id: 7,
    title: 'Dear you, FROM FAN （ペラ1）',
    category: 'Proposal',
    duration: '1週間',
    technology: ['PowerPoint', 'Unity'],
    description: 'バンダイナムコスタジオ様の主催の「ゲームアイディア創造コンテスト！」にて入賞',
    detailedDescription: {
      overview: '株式会社バンダイナムコスタジオ様の「ゲームデザイナーから学ぶ、ゲームアイディア創造コンテスト！」に応募し入賞。',
      gameContent: 'ファンが推しアーティストに「想いを届ける」をテーマにしたアドベンチャーパズルゲームの企画書（ペラ1）。',
      role: '企画立案から企画書（ペラ1）の作成まで一人で担当。',
    },
    features: ['企画書', 'アドベンチャーパズルゲーム'],
    image: `${BASE}/Image/works/Dear/Dear.png`,
    links: {
      pdf: `${BASE}/PDF/Dear.pdf`,
    },
  },
  {
    id: 8,
    title: 'チャットアプリ',
    category: 'Web App',
    duration: '1週間',
    technology: ['HTML', 'JavaScript', 'Nuxt.js', 'Vuetify', 'Tailwind CSS', 'Firebase'],
    description: 'インターンで制作したチャットWebアプリケーション',
    detailedDescription: {
      overview: 'インターンでのフロントエンド開発の技術習得を目的として制作。',
      gameContent: 'Nuxt.jsとFirebaseを使用して制作したリアルタイムチャットアプリケーション。',
      role: 'リアルタイム通信・ユーザー管理・認証機能の実装を担当。',
    },
    features: ['リアルタイムチャット', 'ログイン機能', 'データベースを活用したデータの保存'],
    image: `${BASE}/Image/works/chatApp/chatApp.png`,
    links: {
      github: 'https://github.com/Taka100822/chat-app',
    },
  },
  {
    id: 9,
    title: '冷蔵庫管理アプリ',
    category: 'Web App',
    duration: '3ヶ月',
    technology: ['Vue.js', 'Nuxt.js'],
    description: 'フロントエンドの一部分を担当したチーム開発プロジェクト',
    detailedDescription: {
      overview: '初めてのチーム開発経験として制作。Git運用や役割分担・コードレビューの経験を積んだ。',
      gameContent: 'チーム開発で制作した冷蔵庫の食材管理Webアプリケーション。',
      role: '主にフロントエンドの実装を担当し、UI/UXの設計と実装に携わった。',
    },
    features: ['初チーム開発', 'フロントエンド担当', 'UI/UX設計'],
    image: `${BASE}/Image/works/fridge-manager/fridge-manager.png`,
    links: {
      github: 'https://github.com/KIT-HI-ProgrammingContestGroupC/fridge-manager',
    },
  },
];
